language: cpp
sudo: true
dist: trusty
compiler:
  - g++
os:
  - linux
branches:
  only:
    - master
env:
  - TRAVIS_CONTEXT="WithCoveralls"
  - TRAVIS_CONTEXT="NoCoveralls"
  - TRAVIS_CONTEXT="WithValgrind"
before_install: 
  - export HOME=`pwd`
  - export PATH_DEV=${HOME}/dev
  - export HOME_FRAMEWORKS=${HOME}/frameworks
  - export HOME_LIB=${HOME}/lib
  - export HOME_BIN=${HOME}/bin
  - export HOME_ETC=${HOME}/etc
  - export HOME_INC=${HOME}/include
  - export PATH=${HOME_BIN}:${PATH}
  - export LD_LIBRARY_PATH=${HOME_LIB}:/usr/local/lib:${LD_LIBRARY_PATH}
  - ls -l ${HOME} && pwd
  - echo ${TRAVIS_CONTEXT}
  - echo ${TRAVIS_JOB_ID}
  - echo ${COVERALLS_TOKEN}
before_script:
  - echo ${LD_LIBRARY_PATH}
before_deploy: true
install: ${HOME}/travis_scripts/install.bash
script: ${HOME}/travis_scripts/build.bash
after_deploy: true
after_success: ${HOME}/travis_scripts/test.bash
after_failure: false
after_script:
 - echo 'After Script is here'
notifications:
  email: true
