language: cpp
sudo: true
dist: trusty
compiler:
  - gcc
  - g++
os:
  - linux
branches:
  only:
    - master
env: 
  global
    - export HOME=`pwd`
    - export HOME_FRAMEWORKS=${HOME}/frameworks
    - export HOME_LIB=${HOME}/lib
    - export HOME_BIN=${HOME}/bin
    - export HOME_ETC=${HOME}/etc
    - export HOME_INC=${HOME}/include
    - export PATH=${HOME_BIN}:${PATH}
    - export LD_LIBRARY_PATH=${HOME_LIB}:/usr/local/lib:${LD_LIBRARY_PATH}
    - export PATH_DEV=${HOME}/dev
before_install: true
before_script: true
before_deploy: true
install:
  - ${HOME}/install.bash
script:
  - echo "For Future: make test, gendoc"
  - ${HOME}/build.bash
deploy:
  - echo "For Future: make dist"
after_install: true
after_deploy:
  - echo "For Future: make clean and check everything was removed"
after_success:
  - ${HOME}/test.bash
after_failure: false
after_script: true
  - echo "For Future: make run"
notifications:
  email: true
