language: cpp
sudo: true
dist: trusty
compiler:
  - g++
os:
  - linux
branches:
  only:
    - master
env:
  - TRAVIS_CONTEXT="WithCoveralls"
  - TRAVIS_CONTEXT="NoCoveralls"
  - TRAVIS_CONTEXT="WithValgrind"
before_install:
  - export HOME=`pwd`
  - export PATH_DEV=${HOME}/dev
  - export HOME_FRAMEWORKS=${HOME}/frameworks
  - export HOME_LIB=${HOME}/lib
  - export HOME_BIN=${HOME}/bin
  - export HOME_ETC=${HOME}/etc
  - export HOME_INC=${HOME}/include
  - export HOME_TMP=${HOME}/tmp
  - export PATH=${HOME_BIN}:${PATH}
  - export LD_LIBRARY_PATH=${HOME_LIB}:/usr/local/lib:${LD_LIBRARY_PATH}
  - echo ${TRAVIS_CONTEXT}
  - echo ${TRAVIS_JOB_ID}
  - echo ${COVERALLS_TOKEN}
install: ${HOME}/travis_scripts/install.bash
before_script: true
script: ${HOME}/travis_scripts/build.bash
after_success: ${HOME}/travis_scripts/run.bash
after_failure: false
after_script:
  - ${HOME}/travis_scripts/test.bash
before_deploy: true
deploy:
  skip_cleanup: true
after_deploy: true
notifications:
  email:
    recipients:
      - garcia.yann@gmail.com
    on_success: always
    on_failure: always
