language: cpp
sudo: false
dist: trusty
compiler:
  - gcc
  - g++
os:
  - linux
branches:
  only:
    - master
env: 
  global
    - HOME_FRAMEWORKS=${HOME}/frameworks
    - HOME_LIB=${HOME}/lib
    - HOME_BIN=${HOME}/bin
    - HOME_ETC=${HOME}/etc
    - HOME_INC=${HOME}/include
    - PATH=${HOME_BIN}:${PATH}
    - LD_LIBRARY_PATH=${HOME_LIB}:/usr/local/lib:${LD_LIBRARY_PATH}
    - PATH_DEV=~/repo/dev
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y
  - wget "https://launchpad.net/gcc-arm-embedded/+download/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2"
  - tar xvzf gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2 ${HOME_FRAMEWORKS}
  - wget https://downloads.sourceforge.net/project/cpptest/cpptest/cpptest-1.1.2/cpptest-1.1.2.tar.gz
  - tar xvzf cpptest-1.1.2.tar.gz ${HOME_FRAMEWORKS}
install:
  - find ${HOME_FRAMEWORKS}/cpptest-1.1.2/ -name "*.h*" -type f -exec sed -i 's/auto_ptr/unique_ptr/g' {} \;
  - find ${HOME_FRAMEWORKS}/cpptest-1.1.2/ -name "*.c*" -type f -exec sed -i 's/auto_ptr/unique_ptr/g' {} \;
  - bash ./install.bash
before_script:
  - gcc --version
  - gcc -v
  - g++ -v
script: bash ./build.bash
after_script: true
after_success: true
after_failure: true
#before_deploy: true
#deploy: true
#after_deploy: true
notifications:
  email: true
