language: cpp
sudo: true
dist: trusty
compiler:
  - g++
os:
  - linux
branches:
  only:
    - master
env:
  - TRAVIS_CONTEXT="NoCoveralls"
  - TRAVIS_CONTEXT="WithValgrind"
#  - TRAVIS_CONTEXT="WithCoveralls"
#  - TRAVIS_CONTEXT="LinuxHW"
before_install:
  - export HOME=`pwd`
install:
  - . ${HOME}/travis_scripts/install.bash
before_script: true
script:
  - ${HOME}/travis_scripts/build.bash
after_success:
  - ${HOME}/travis_scripts/run.bash
after_failure: false
after_script: true
before_deploy:
  - ${HOME}/travis_scripts/test.bash
- - ${HOME}/travis_scripts/deploy.bash
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
after_deploy: true
notifications:
  email:
    recipients:
      - garcia.yann@gmail.com
    on_success: always
    on_failure: always
