language: cpp
sudo: true
dist: trusty
compiler:
  - g++
os:
  - linux
branches:
  only:
    - master
env:
  - TRAVIS_CONTEXT="WithCoveralls"
  - TRAVIS_CONTEXT="NoCoveralls"
before_install: . ./travis_scripts/before_install.bash
before_script:
  - echo ${LD_LIBRARY_PATH}
before_deploy: true
install: ${HOME}/travis_scripts/install.bash
script: ${HOME}/travis_scripts/build.bash
after_deploy: true
after_success: ${HOME}/travis_scripts/test.bash
after_failure: false
after_script:
 - echo 'After Script is here'
notifications:
  email: true
